### ISSUE TITLE
Not getting titles or authors

### ISSUE THREAD

**Issue by scientia-ipsa** [xfause/cnki_spider#1]
Hello,
This works great for me but it's only getting abstracts. Can you have it collect title and authors in the txt file also?
Example: cnki.com.cn/Article/CJFDTOTAL-GXXB202002001.htm
Thank you

**Comment by xfause** [comment]
> Hello,
> This works great for me but it's only getting abstracts. Can you have it collect title and authors in the txt file also?
> Example: cnki.com.cn/Article/CJFDTOTAL-GXXB202002001.htm
> Thank you

Done.
Add title and authors in file content, rename out filename
